import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'pt' | 'es' | 'de' | 'zh' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Auto-detect language from browser
const detectLanguage = (): Language => {
  // First try localStorage
  const stored = localStorage.getItem('lang') as Language;
  if (stored && ['en', 'pt', 'es', 'de', 'zh', 'fr'].includes(stored)) {
    return stored;
  }
  
  // Then browser language
  const browserLang = (navigator.language || 'pt').slice(0, 2) as Language;
  if (['en', 'pt', 'es', 'de', 'zh', 'fr'].includes(browserLang)) {
    return browserLang;
  }
  
  return 'pt'; // Default to Portuguese
};

const translations = {
  en: {
    header: {
      dashboard: 'Dashboard',
      myBookings: 'My Bookings',
      sitterDashboard: 'Sitter Dashboard',
      knowOurSitters: 'Know Our Sitters',
      bookNow: 'Book Now',
      admin: 'Admin',
      signOut: 'Sign Out',
      login: 'Login',
      signUpAsSitter: 'Sign Up as Sitter',
      enterRegister: 'Enter/Register',
      profile: 'Profile',
      findSitters: 'Find Sitters',
      becomeASitter: 'Become a Sitter',
      signIn: 'Sign In',
      signUp: 'Sign Up',
    },
    
    // Search
    'search.findPerfectSitter': 'Find Your Perfect Pet Sitter',
    'search.browseFavoritesFirst': 'Browse verified pet and house sitters. Your favorites appear first!',
    'search.browseSignInToSave': 'Browse verified pet and house sitters. Sign in to save favorites!',
    'search.signInToFavorite': 'Please sign in to favorite sitters',
    'search.removedFromFavorites': 'Removed from favorites',
    'search.addedToFavorites': 'Added to favorites',
    'search.failedToUpdateFavorites': 'Failed to update favorites',
    'search.filteringComingSoon': 'Filtering functionality coming soon!',
    'search.filters': 'Filters',
    'search.advancedFilteringComingSoon': 'Advanced filtering coming soon! Currently showing all verified sitters.',
    'search.verifiedSittersFound': 'verified sitters found',
    'search.noSittersFound': 'No sitters found',
    'search.tryAdjustingFilters': 'Try adjusting your filters or check back later for more sitters.',
    'search.refreshResults': 'Refresh Results',
    
    // Landing
    'landing.trustedSitterIn': 'Your trusted sitter in',
    'landing.threeMinutes': '3 minutes',
    'landing.connectWithVerified': 'Connect with verified pet and house sitters in Portugal\'s Silver Coast. Safe, transparent, and reliable care for your beloved pets and home.',
    'landing.bookNow': 'Book Now',
    'landing.knowOurSitters': 'Know Our Sitters',
    'landing.becomeASitter': 'Become a Sitter',
    'landing.verifiedSitters': 'Verified sitters',
    'landing.securePayments': 'Secure payments',
    'landing.support247': '24/7 support',
    'landing.howItWorks': 'How it works',
    'landing.bookTrustedSitters': 'Book trusted pet and house sitters in just a few simple steps',
    'landing.step1Title': '1. Find a Sitter',
    'landing.step1Description': 'Browse verified sitters in your area. View profiles, reviews, and availability.',
    'landing.step2Title': '2. Book',
    'landing.step2Description': 'Send a booking request with your dates and requirements. Pay securely online.',
    'landing.step3Title': '3. Relax',
    'landing.step3Description': 'Your pets and home are in safe hands. Get updates and enjoy your time away.',
    'landing.readyToFind': 'Ready to find your perfect sitter?',
    'landing.joinHundreds': 'Join hundreds of pet owners in the Silver Coast who trust us with their beloved companions.',
    'landing.getStartedToday': 'Get Started Today',
    'landing.petFriendlyLocations': 'Pet Friendly Locations',
    'landing.discoverAmazing': 'Discover amazing pet-friendly places across the Silver Coast region',
    'landing.obidosDescription': 'Medieval charm with pet-friendly cafés and historic walking paths',
    'landing.exploreObidos': 'Explore Óbidos',
    'landing.caldasDescription': 'Thermal parks and gardens perfect for relaxing walks',
    'landing.exploreCaldas': 'Explore Caldas',
    'landing.bombarralDescription': 'Peaceful countryside with spacious parks and trails',
    'landing.exploreBombarral': 'Explore Bombarral',
    'landing.penicheDescription': 'Beautiful beaches and coastal restaurants welcoming pets',
    'landing.explorePeniche': 'Explore Peniche',
    'landing.trustedServices': 'Trusted pet and house sitting services in Portugal\'s Silver Coast region.',
    'landing.services': 'Services',
    'landing.petSitting': 'Pet Sitting',
    'landing.houseSitting': 'House Sitting',
    'landing.dogWalking': 'Dog Walking',
    'landing.emergencyCare': 'Emergency Care',
    'landing.locations': 'Locations',
    'landing.support': 'Support',
    'landing.helpCenter': 'Help Center',
    'landing.contactUs': 'Contact Us',
    'landing.safety': 'Safety',
    'landing.termsConditions': 'Terms & Conditions',
    
    // Auth Page
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome Back',
    'auth.joinCommunity': 'Join our community of trusted sitters',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.createStrongPassword': 'Create a strong password',
    'auth.enterPassword': 'Enter your password',
    'auth.signIn': 'Sign In',
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.dontHaveAccount': "Don't have an account? Sign up",
    'auth.forgotPassword': 'Forgot your password?',
    'auth.backToHome': '← Back to home',
    'auth.termsAgreement': 'By creating an account, you agree to our Terms of Service and Privacy Policy.',
    'auth.resetPassword': 'Reset Password',
    'auth.enterEmailReset': 'Enter your email to receive reset instructions',
    'auth.sendResetEmail': 'Send Reset Email',
    'auth.backToSignIn': '← Back to sign in',
    'auth.enterEmailError': 'Please enter your email address',
    'auth.resetEmailSent': 'Password reset email sent! Check your inbox.',
    'auth.enterNameError': 'Please enter your name',
    'auth.emailAlreadyRegistered': 'This email is already registered. Try signing in instead.',
    'auth.accountCreated': 'Account created! Please check your email to verify your account.',
    'auth.invalidCredentials': 'Invalid email or password. Please try again.',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.manageSittersAndApplications': 'Manage sitters and applications',
    'admin.pendingApplications': 'Pending Applications',
    'admin.activeSitters': 'Active Sitters',
    'admin.totalApplications': 'Total Applications',
    'admin.allSitters': 'All Sitters',
    'admin.applications': 'Applications',
    'admin.manageSitters': 'Manage Sitters',
    'admin.manageBookings': 'Manage Bookings',
    'admin.sitterApplications': 'Sitter Applications',
    'admin.noApplicationsYet': 'No applications yet',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.addSitter': 'Add Sitter',
    'admin.noSittersRegistered': 'No sitters registered yet',
    'admin.verified': 'Verified',
    'admin.unverified': 'Unverified',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.activate': 'Activate',
    'admin.deactivate': 'Deactivate',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.deleteConfirmation': 'Are you sure you want to delete sitter "{name}"? This action cannot be undone.',
    'admin.deleteSuccess': 'Sitter "{name}" deleted successfully',
    'admin.deleteError': 'Error deleting sitter',
    
    // Common
    'common.price': 'Price',
    'common.phone': 'Phone',
    'common.emergency': 'Emergency',
    'common.insurance': 'Insurance',
    'common.applied': 'Applied',
    'common.experience': 'experience',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.day': 'day',
    'common.hour': 'hour',
    'common.pending': 'pending',
    'common.approved': 'approved',
    'common.rejected': 'rejected',
    'common.error': 'An error occurred',
    'common.locale': 'en-US',
    'common.rating': 'rating',
    
    // Dashboard
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.manageBookings': 'Manage your bookings and find trusted sitters',
    'dashboard.browseSitters': 'Browse Sitters',
    'dashboard.requestNewSitting': 'Request New Sitting',
    'dashboard.pendingConfirmation': 'Pending Confirmation',
    'dashboard.upcomingBookings': 'Upcoming Bookings',
    'dashboard.completedBookings': 'Completed Bookings',
    'dashboard.noBookingsYet': 'No bookings yet',
    'dashboard.startFindingSitter': 'Start by finding a trusted sitter in your area',
    'dashboard.bookASitter': 'Book a Sitter',
    'dashboard.pastBookings': 'Past Bookings',
    'dashboard.cancelBooking': 'Cancel Booking',
    'dashboard.leaveReview': 'Leave Review',
    'dashboard.viewDetails': 'View Details',
    'dashboard.notes': 'Notes',
    'dashboard.bookingCancelled': 'Booking cancelled successfully',
    'dashboard.failedCancelBooking': 'Failed to cancel booking',
    'dashboard.failedLoadBookings': 'Failed to load bookings',
    
    // Become a Sitter
    'becomeSitter.title': 'Become a Sitter',
    'becomeSitter.back': 'Back',
    'becomeSitter.stepOf': 'Step {step} of {total}',
    'becomeSitter.complete': '{percent}% complete',
    'becomeSitter.personalInfo': 'Personal Information',
    'becomeSitter.firstName': 'First Name',
    'becomeSitter.lastName': 'Last Name',
    'becomeSitter.phoneNumber': 'Phone Number',
    'becomeSitter.location': 'Location',
    'becomeSitter.selectLocation': 'Select your location',
    'becomeSitter.otherSilverCoast': 'Other (Silver Coast)',
    'becomeSitter.yearsExperience': 'Years of Experience',
    'becomeSitter.selectExperience': 'Select experience level',
    'becomeSitter.lessThan1Year': 'Less than 1 year',
    'becomeSitter.servicesPricing': 'Services & Pricing',
    'becomeSitter.servicesYouOffer': 'Services You Offer',
    'becomeSitter.pricePerDay': 'Price Per Day (€)',
    'becomeSitter.recommendedRange': 'Recommended range: €25-€50 per day',
    'becomeSitter.aboutYou': 'About You',
    'becomeSitter.aboutYouPlaceholder': 'Tell potential clients about your experience, what makes you special, and why they should trust you with their pets...',
    'becomeSitter.aboutYouDescription': 'Describe your experience, personality, and what makes you the perfect pet sitter.',
    'becomeSitter.finalDetails': 'Final Details',
    'becomeSitter.emergencyContact': 'Emergency Contact',
    'becomeSitter.emergencyContactPlaceholder': 'Name and phone number',
    'becomeSitter.profilePhoto': 'Profile Photo',
    'becomeSitter.hasInsurance': 'I have liability insurance',
    'becomeSitter.agreeTerms': 'I agree to the Terms of Service and Privacy Policy',
    'becomeSitter.whatHappensNext': 'What happens next?',
    'becomeSitter.reviewWithin24h': "We'll review your application within 24 hours",
    'becomeSitter.backgroundCheck': 'Background check and reference verification',
    'becomeSitter.videoInterview': 'Video interview with our team',
    'becomeSitter.profileApproval': 'Profile approval and activation',
    'becomeSitter.cancel': 'Cancel',
    'becomeSitter.previous': 'Previous',
    'becomeSitter.next': 'Next',
    'becomeSitter.submitting': 'Submitting...',
    'becomeSitter.submitApplication': 'Submit Application',
    'becomeSitter.applicationSubmitted': 'Application submitted successfully!',
    'becomeSitter.reviewDescription': "We'll review your profile and get back to you within 24 hours.",
    'becomeSitter.failedSubmit': 'Failed to submit application. Please try again.',
    'becomeSitter.failedLoadServices': 'Failed to load services',
    
    // Sitter Dashboard
    'sitter.dashboard': 'Sitter Dashboard',
    'sitter.manageBookings': 'Manage your bookings',
    'sitter.newRequests': 'New Requests',
    'sitter.upcoming': 'Upcoming',
    'sitter.completed': 'Completed',
    'sitter.pastBookings': 'Past Bookings',
    'sitter.noBookings': 'No bookings yet',
    'sitter.waitingForRequests': 'Waiting for booking requests',
    'sitter.editProfile': 'Edit Profile',
    'sitter.bookingAccepted': 'Booking accepted successfully',
    'sitter.bookingDeclined': 'Booking declined',
    'sitter.errorAcceptingBooking': 'Error accepting booking',
    'sitter.errorDecliningBooking': 'Error declining booking',
    'sitter.errorFetchingBookings': 'Error loading bookings',
    'sitter.notRegistered': 'You are not registered as a sitter',
  },
  pt: {
    // Header
    'header.dashboard': 'Painel',
    'header.knowOurSitters': 'Conhece os Nossos Sitters',
    'header.bookNow': 'Reservar Agora',
    'header.admin': 'Admin',
    'header.signOut': 'Sair',
    'header.login': 'Entrar',
    'header.signUpAsSitter': 'Registar como Sitter',
    'header.enterRegister': 'Entrar/Registar',
    'header.profile': 'Perfil',
    'header.myBookings': 'As Minhas Reservas',
    
    // Search
    'search.findPerfectSitter': 'Encontre o Seu Pet Sitter Perfeito',
    'search.browseFavoritesFirst': 'Explore sitters verificados de animais e casa. Os seus favoritos aparecem primeiro!',
    'search.browseSignInToSave': 'Explore sitters verificados de animais e casa. Entre para guardar favoritos!',
    'search.signInToFavorite': 'Por favor entre para favoritar sitters',
    'search.removedFromFavorites': 'Removido dos favoritos',
    'search.addedToFavorites': 'Adicionado aos favoritos',
    'search.failedToUpdateFavorites': 'Falha ao atualizar favoritos',
    'search.filteringComingSoon': 'Funcionalidade de filtros em breve!',
    'search.filters': 'Filtros',
    'search.advancedFilteringComingSoon': 'Filtros avançados em breve! Atualmente mostrando todos os sitters verificados.',
    'search.verifiedSittersFound': 'sitters verificados encontrados',
    'search.noSittersFound': 'Nenhum sitter encontrado',
    'search.tryAdjustingFilters': 'Tente ajustar os seus filtros ou volte mais tarde para mais sitters.',
    'search.refreshResults': 'Atualizar Resultados',
    
    // Landing
    'landing.trustedSitterIn': 'O seu sitter de confiança em',
    'landing.threeMinutes': '3 minutos',
    'landing.connectWithVerified': 'Conecte-se com sitters verificados de animais e casa na Costa de Prata. Cuidado seguro, transparente e confiável para os seus animais e casa.',
    'landing.bookNow': 'Reservar Agora',
    'landing.knowOurSitters': 'Conheça os Nossos Sitters',
    'landing.becomeASitter': 'Tornar-me Sitter',
    'landing.verifiedSitters': 'Sitters verificados',
    'landing.securePayments': 'Pagamentos seguros',
    'landing.support247': 'Suporte 24/7',
    'landing.howItWorks': 'Como funciona',
    'landing.bookTrustedSitters': 'Reserve sitters de confiança em apenas alguns passos simples',
    'landing.step1Title': '1. Encontre um Sitter',
    'landing.step1Description': 'Explore sitters verificados na sua área. Veja perfis, avaliações e disponibilidade.',
    'landing.step2Title': '2. Reserve',
    'landing.step2Description': 'Envie um pedido de reserva com as suas datas e requisitos. Pague online com segurança.',
    'landing.step3Title': '3. Relaxe',
    'landing.step3Description': 'Os seus animais e casa estão em boas mãos. Receba atualizações e desfrute do seu tempo.',
    'landing.readyToFind': 'Pronto para encontrar o seu sitter perfeito?',
    'landing.joinHundreds': 'Junte-se a centenas de donos de animais na Costa de Prata que confiam em nós os seus companheiros.',
    'landing.getStartedToday': 'Comece Hoje',
    'landing.petFriendlyLocations': 'Locais Pet-Friendly',
    'landing.discoverAmazing': 'Descubra lugares incríveis pet-friendly na região da Costa de Prata',
    'landing.obidosDescription': 'Charme medieval com cafés pet-friendly e caminhos históricos',
    'landing.exploreObidos': 'Explorar Óbidos',
    'landing.caldasDescription': 'Parques termais e jardins perfeitos para passeios relaxantes',
    'landing.exploreCaldas': 'Explorar Caldas',
    'landing.bombarralDescription': 'Paisagem rural tranquila com parques e trilhos espaçosos',
    'landing.exploreBombarral': 'Explorar Bombarral',
    'landing.penicheDescription': 'Belas praias e restaurantes costeiros que recebem animais',
    'landing.explorePeniche': 'Explorar Peniche',
    'landing.trustedServices': 'Serviços de confiança de pet sitting e house sitting na região da Costa de Prata.',
    'landing.services': 'Serviços',
    'landing.petSitting': 'Pet Sitting',
    'landing.houseSitting': 'House Sitting',
    'landing.dogWalking': 'Passeio de Cães',
    'landing.emergencyCare': 'Cuidado de Emergência',
    'landing.locations': 'Localizações',
    'landing.support': 'Apoio',
    'landing.helpCenter': 'Centro de Ajuda',
    'landing.contactUs': 'Contacte-nos',
    'landing.safety': 'Segurança',
    'landing.termsConditions': 'Termos e Condições',
    
    // Auth Page  
    'auth.createAccount': 'Criar Conta',
    'auth.welcomeBack': 'Bem-vindo de Volta',
    'auth.joinCommunity': 'Junte-se à nossa comunidade de sitters de confiança',
    'auth.signInToAccount': 'Entre na sua conta',
    'auth.fullName': 'Nome Completo',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.createStrongPassword': 'Crie uma palavra-passe forte',
    'auth.enterPassword': 'Digite a sua palavra-passe',
    'auth.signIn': 'Entrar',
    'auth.alreadyHaveAccount': 'Já tem conta? Entre',
    'auth.dontHaveAccount': 'Não tem conta? Registe-se',
    'auth.forgotPassword': 'Esqueceu-se da palavra-passe?',
    'auth.backToHome': '← Voltar ao início',
    'auth.termsAgreement': 'Ao criar uma conta, concorda com os nossos Termos de Serviço e Política de Privacidade.',
    'auth.resetPassword': 'Recuperar Palavra-passe',
    'auth.enterEmailReset': 'Introduza o seu email para receber instruções de recuperação',
    'auth.sendResetEmail': 'Enviar Email de Recuperação',
    'auth.backToSignIn': '← Voltar ao login',
    'auth.enterEmailError': 'Por favor introduza o seu email',
    'auth.resetEmailSent': 'Email de recuperação enviado! Verifique a sua caixa de entrada.',
    'auth.enterNameError': 'Por favor introduza o seu nome',
    'auth.emailAlreadyRegistered': 'Este email já está registado. Tente fazer login.',
    'auth.accountCreated': 'Conta criada! Verifique o seu email para confirmar a conta.',
    'auth.invalidCredentials': 'Email ou palavra-passe inválidos. Tente novamente.',
    
    // Admin Dashboard
    'admin.dashboard': 'Painel de Administração',
    'admin.manageSittersAndApplications': 'Gerir sitters e candidaturas',
    'admin.pendingApplications': 'Candidaturas Pendentes',
    'admin.activeSitters': 'Sitters Ativos',
    'admin.totalApplications': 'Total de Candidaturas',
    'admin.allSitters': 'Todos os Sitters',
    'admin.applications': 'Candidaturas',
    'admin.manageSitters': 'Gerir Sitters',
    'admin.manageBookings': 'Gerir Reservas',
    'admin.sitterApplications': 'Candidaturas de Sitter',
    'admin.noApplicationsYet': 'Ainda não há candidaturas',
    'admin.approve': 'Aprovar',
    'admin.reject': 'Rejeitar',
    'admin.addSitter': 'Adicionar Sitter',
    'admin.noSittersRegistered': 'Ainda não há sitters registados',
    'admin.verified': 'Verificado',
    'admin.unverified': 'Não Verificado',
    'admin.active': 'Ativo',
    'admin.inactive': 'Inativo',
    'admin.activate': 'Ativar',
    'admin.deactivate': 'Desativar',
    'admin.edit': 'Editar',
    'admin.delete': 'Apagar',
    'admin.deleteConfirmation': 'Tem a certeza que quer apagar o sitter "{name}"? Esta ação não pode ser desfeita.',
    'admin.deleteSuccess': 'Sitter "{name}" apagado com sucesso',
    'admin.deleteError': 'Erro ao apagar sitter',
    
    // Common
    'common.price': 'Preço',
    'common.phone': 'Telefone',
    'common.emergency': 'Emergência',
    'common.insurance': 'Seguro',
    'common.applied': 'Candidatou-se',
    'common.experience': 'experiência',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.day': 'dia',
    'common.hour': 'hora',
    'common.pending': 'pendente',
    'common.approved': 'aprovado',
    'common.rejected': 'rejeitado',
    'common.error': 'Ocorreu um erro',
    'common.locale': 'pt-PT',
    'common.rating': 'avaliação',
    
    // Dashboard
    'dashboard.welcomeBack': 'Bem-vindo de volta',
    'dashboard.manageBookings': 'Gira as suas reservas e encontre sitters de confiança',
    'dashboard.browseSitters': 'Explorar Sitters',
    'dashboard.requestNewSitting': 'Nova Reserva',
    'dashboard.pendingConfirmation': 'Confirmação Pendente',
    'dashboard.upcomingBookings': 'Próximas Reservas',
    'dashboard.completedBookings': 'Reservas Concluídas',
    'dashboard.noBookingsYet': 'Ainda sem reservas',
    'dashboard.startFindingSitter': 'Comece por encontrar um sitter de confiança na sua área',
    'dashboard.bookASitter': 'Reservar um Sitter',
    'dashboard.pastBookings': 'Reservas Anteriores',
    'dashboard.cancelBooking': 'Cancelar Reserva',
    'dashboard.leaveReview': 'Deixar Avaliação',
    'dashboard.viewDetails': 'Ver Detalhes',
    'dashboard.notes': 'Notas',
    'dashboard.bookingCancelled': 'Reserva cancelada com sucesso',
    'dashboard.failedCancelBooking': 'Erro ao cancelar reserva',
    'dashboard.failedLoadBookings': 'Erro ao carregar reservas',
    
    // Become a Sitter
    'becomeSitter.title': 'Tornar-me Sitter',
    'becomeSitter.back': 'Voltar',
    'becomeSitter.stepOf': 'Passo {step} de {total}',
    'becomeSitter.complete': '{percent}% completo',
    'becomeSitter.personalInfo': 'Informação Pessoal',
    'becomeSitter.firstName': 'Primeiro Nome',
    'becomeSitter.lastName': 'Último Nome',
    'becomeSitter.phoneNumber': 'Número de Telefone',
    'becomeSitter.location': 'Localização',
    'becomeSitter.selectLocation': 'Selecione a sua localização',
    'becomeSitter.otherSilverCoast': 'Outro (Costa de Prata)',
    'becomeSitter.yearsExperience': 'Anos de Experiência',
    'becomeSitter.selectExperience': 'Selecione nível de experiência',
    'becomeSitter.lessThan1Year': 'Menos de 1 ano',
    'becomeSitter.servicesPricing': 'Serviços e Preços',
    'becomeSitter.servicesYouOffer': 'Serviços que Oferece',
    'becomeSitter.pricePerDay': 'Preço por Dia (€)',
    'becomeSitter.recommendedRange': 'Intervalo recomendado: €25-€50 por dia',
    'becomeSitter.aboutYou': 'Sobre Si',
    'becomeSitter.aboutYouPlaceholder': 'Conte aos potenciais clientes sobre a sua experiência, o que o torna especial, e por que devem confiar-lhe os seus animais...',
    'becomeSitter.aboutYouDescription': 'Descreva a sua experiência, personalidade, e o que o torna o pet sitter perfeito.',
    'becomeSitter.finalDetails': 'Detalhes Finais',
    'becomeSitter.emergencyContact': 'Contacto de Emergência',
    'becomeSitter.emergencyContactPlaceholder': 'Nome e número de telefone',
    'becomeSitter.profilePhoto': 'Foto de Perfil',
    'becomeSitter.hasInsurance': 'Tenho seguro de responsabilidade civil',
    'becomeSitter.agreeTerms': 'Concordo com os Termos de Serviço e Política de Privacidade',
    'becomeSitter.whatHappensNext': 'O que acontece a seguir?',
    'becomeSitter.reviewWithin24h': 'Vamos rever a sua candidatura em 24 horas',
    'becomeSitter.backgroundCheck': 'Verificação de antecedentes e referências',
    'becomeSitter.videoInterview': 'Entrevista por vídeo com a nossa equipa',
    'becomeSitter.profileApproval': 'Aprovação e ativação do perfil',
    'becomeSitter.cancel': 'Cancelar',
    'becomeSitter.previous': 'Anterior',
    'becomeSitter.next': 'Seguinte',
    'becomeSitter.submitting': 'A enviar...',
    'becomeSitter.submitApplication': 'Enviar Candidatura',
    'becomeSitter.applicationSubmitted': 'Candidatura enviada com sucesso!',
    'becomeSitter.reviewDescription': 'Vamos rever o seu perfil e responder em 24 horas.',
    'becomeSitter.failedSubmit': 'Erro ao enviar candidatura. Tente novamente.',
    'becomeSitter.failedLoadServices': 'Erro ao carregar serviços',
    
    // Sitter Dashboard
    'sitter.dashboard': 'Painel do Sitter',
    'sitter.manageBookings': 'Gerir as suas reservas',
    'sitter.newRequests': 'Novos Pedidos',
    'sitter.upcoming': 'Próximas',
    'sitter.completed': 'Concluídas',
    'sitter.pastBookings': 'Reservas Anteriores',
    'sitter.noBookings': 'Sem reservas',
    'sitter.waitingForRequests': 'À espera de pedidos',
    'sitter.editProfile': 'Editar Perfil',
    'sitter.bookingAccepted': 'Reserva aceite com sucesso',
    'sitter.bookingDeclined': 'Reserva recusada',
    'sitter.errorAcceptingBooking': 'Erro ao aceitar reserva',
    'sitter.errorDecliningBooking': 'Erro ao recusar reserva',
    'sitter.errorFetchingBookings': 'Erro ao carregar reservas',
    'sitter.notRegistered': 'Não está registado como sitter',
  },
  es: {
    // Header
    'header.dashboard': 'Panel',
    'header.knowOurSitters': 'Conoce Nuestros Cuidadores',
    'header.bookNow': 'Reservar Ahora',
    'header.admin': 'Admin',
    'header.signOut': 'Cerrar Sesión',
    'header.login': 'Iniciar Sesión',
    'header.signUpAsSitter': 'Registrarse como Cuidador',
    
    // Auth Page
    'auth.createAccount': 'Crear Cuenta',
    'auth.welcomeBack': 'Bienvenido de Vuelta',
    'auth.joinCommunity': 'Únete a nuestra comunidad de cuidadores de confianza',
    'auth.signInToAccount': 'Inicia sesión en tu cuenta',
    'auth.fullName': 'Nombre Completo',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.createStrongPassword': 'Crea una contraseña fuerte',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.signIn': 'Iniciar Sesión',
    'auth.alreadyHaveAccount': '¿Ya tienes cuenta? Inicia sesión',
    'auth.dontHaveAccount': '¿No tienes cuenta? Regístrate',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.backToHome': '← Volver al inicio',
    'auth.termsAgreement': 'Al crear una cuenta, aceptas nuestros Términos de Servicio y Política de Privacidad.',
    
    // Other translations would continue here...
    'admin.dashboard': 'Panel de Administración',
    'admin.manageSittersAndApplications': 'Gestionar cuidadores y solicitudes',
    // ... (other Spanish translations)
  },
  de: {
    // German translations
    'header.dashboard': 'Dashboard',
    'header.knowOurSitters': 'Unsere Betreuer Kennenlernen',
    'header.bookNow': 'Jetzt Buchen',
    'auth.createAccount': 'Konto Erstellen',
    'auth.welcomeBack': 'Willkommen Zurück',
    // ... (other German translations)
  },
  zh: {
    // Chinese translations
    'header.dashboard': '仪表板',
    'header.knowOurSitters': '了解我们的看护员',
    'header.bookNow': '立即预订',
    'auth.createAccount': '创建账户',
    'auth.welcomeBack': '欢迎回来',
    // ... (other Chinese translations)
  },
  fr: {
    // French translations
    'header.dashboard': 'Tableau de Bord',
    'header.knowOurSitters': 'Connaître Nos Gardiens',
    'header.bookNow': 'Réserver Maintenant',
    'auth.createAccount': 'Créer un Compte',
    'auth.welcomeBack': 'Bon Retour',
    // ... (other French translations)
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => detectLanguage());

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
