// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apyogunkydkilyzidmve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweW9ndW5reWRraWx5emlkbXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTE4ODksImV4cCI6MjA2OTI2Nzg4OX0.LQU1dwhK2DMTSa6QlepQ22SYPgwnYYy6pQwrUjWtlWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});